# @package diffusion
name: ddpm
_target_: pdi.diffusion.ddpm.DDPM

# Noise schedule
num_timesteps: 500 # 1000
beta_schedule: linear  # or 'cosine'
beta_start: 0.0001
beta_end: 0.02

# Loss
loss_type: l2  # or 'l1', 'huber'
parameterization: eps  # or 'x0', 'v'

# Sampling
clip_denoised: false