micromamba run -n gdiff python scripts/wra/diffusion/train_energy_score.py \
  --dataset wra_medium_outdoor_high_density \
  --backbone portfolio_gnn \
  --hidden 256 --num-layers 8 --gnn-K 2 \
  --inverse-beta 1.0  --energy-mc-samples 8 --num-channel-realizations 50 \
  --num-outer 1000  --inner-steps 10 --inner-steps-max 30 \
  --lr 0.001 --lr-min 1e-05 --batch-size 4 --minibatch-size 128  \
  --dual-step-size 0.05 --dual-lambda-init 10.0 --dual-lambda-max 50.0 \
  --dual-num-channel-realizations 500 \
  --n-samples-per-network 50 \
  --train-mc-samples 8 --rho-max 0.7 --warmup-iters 500 \
  --target-clip-norm 20.0 --target-normalize-eps 0.1 \
  --buffer-capacity 4096 --grad-clip-norm 1.0 \
  --perturb-fraction 0.5  --perturb-x-std 0.1 --perturb-lambda-std 0.5 \
  --num-rollouts-per-outer 1 \
  --prior-mu-min 2.0 --prior-mu-max 10.0 \
  --eval-every 50 --eval-samples 200 --eval-networks 32 --eval-timeslots 500 \
  --seed 42 \
  --label energy_portgnn_normal 